spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;database=EBANK_FAULU
    password: Rootroot@1045
    username: sa


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
server:
  port: 8081

report:
  startDate: "2023-08-01"
  endDate: "2024-01-31"