spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;database=EBANK_FAULU
    password: Rootroot@1045
    username: sa

server:
  port: 8081

report:
  endDate: "2023-08-12"

myapp.scheduler.enabled: true



